Update package.yml

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -13,10 +13,10 @@ jobs:
   build:
     runs-on: ubuntu-22.04
     permissions:
-       contents: write
-       issues: write
-       pull-requests: write
-       id-token: write
+      contents: write
+      issues: write
+      pull-requests: write
+      id-token: write
 
     steps:
       - name: Checkout Repository
@@ -73,11 +73,15 @@ jobs:
           echo "Addon packed as ${ZIP_NAME}"
 
       - name: Upload Release Assets
-        uses: softprops/action-gh-release@v1
-        with:
-          tag_name: "v${{ env.FINAL_VERSION }}"
-          files: |
-            ${GITHUB_WORKSPACE}/DBM-VPUkrainian-${FINAL_VERSION}.zip
+        run: |
+          ZIP_FILE="${GITHUB_WORKSPACE}/DBM-VPUkrainian-${FINAL_VERSION}.zip"
+          if [ -f "$ZIP_FILE" ]; then
+            echo "Uploading release asset: $ZIP_FILE"
+            gh release upload "v${{ env.FINAL_VERSION }}" "$ZIP_FILE" --repo ${{ github.repository }}
+          else
+            echo "File $ZIP_FILE not found, skipping upload."
+            exit 1
+          fi
 
       - name: Create and Upload Package
         uses: BigWigsMods/packager@v2
@@ -95,3 +99,4 @@ jobs:
         with:
           webhook_url: ${{ secrets.WEBHOOK_URL }}
           status: ${{ job.status }}
+
